---
# Source: service-chart/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: jackson-ui
  labels:
    app: jackson
spec:
  selector:
    app: spring-boot-ui # Deployment name tag
  ports:
  - name: http
    port: 8080

